/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductImage } from "./ProductImage";
import { ProductImageCountArgs } from "./ProductImageCountArgs";
import { ProductImageFindManyArgs } from "./ProductImageFindManyArgs";
import { ProductImageFindUniqueArgs } from "./ProductImageFindUniqueArgs";
import { CreateProductImageArgs } from "./CreateProductImageArgs";
import { UpdateProductImageArgs } from "./UpdateProductImageArgs";
import { DeleteProductImageArgs } from "./DeleteProductImageArgs";
import { Product } from "../../product/base/Product";
import { ProductImageService } from "../productImage.service";
@graphql.Resolver(() => ProductImage)
export class ProductImageResolverBase {
  constructor(protected readonly service: ProductImageService) {}

  async _productImagesMeta(
    @graphql.Args() args: ProductImageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductImage])
  async productImages(
    @graphql.Args() args: ProductImageFindManyArgs
  ): Promise<ProductImage[]> {
    return this.service.productImages(args);
  }

  @graphql.Query(() => ProductImage, { nullable: true })
  async productImage(
    @graphql.Args() args: ProductImageFindUniqueArgs
  ): Promise<ProductImage | null> {
    const result = await this.service.productImage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductImage)
  async createProductImage(
    @graphql.Args() args: CreateProductImageArgs
  ): Promise<ProductImage> {
    return await this.service.createProductImage({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ProductImage)
  async updateProductImage(
    @graphql.Args() args: UpdateProductImageArgs
  ): Promise<ProductImage | null> {
    try {
      return await this.service.updateProductImage({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProductImage)
  async deleteProductImage(
    @graphql.Args() args: DeleteProductImageArgs
  ): Promise<ProductImage | null> {
    try {
      return await this.service.deleteProductImage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: ProductImage
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
