/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryUpdateManyWithoutProductsInput } from "./CategoryUpdateManyWithoutProductsInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsNumber,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { OrderUpdateManyWithoutProductsInput } from "./OrderUpdateManyWithoutProductsInput";
import { ProductImageUpdateManyWithoutProductsInput } from "./ProductImageUpdateManyWithoutProductsInput";
import { PromotionUpdateManyWithoutProductsInput } from "./PromotionUpdateManyWithoutProductsInput";
import { SliderUpdateManyWithoutProductsInput } from "./SliderUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CategoryUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CategoryUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  category?: CategoryUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionRs?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionRu?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => ProductImageUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductImageUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductImageUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  productImages?: ProductImageUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => PromotionUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PromotionUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PromotionUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  promotions?: PromotionUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sku?: string | null;

  @ApiProperty({
    required: false,
    type: () => SliderUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => SliderUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => SliderUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  sliders?: SliderUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleRs?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleRu?: string | null;
}

export { ProductUpdateInput as ProductUpdateInput };
