/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryCreateNestedManyWithoutProductsInput } from "./CategoryCreateNestedManyWithoutProductsInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsNumber,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { OrderCreateNestedManyWithoutProductsInput } from "./OrderCreateNestedManyWithoutProductsInput";
import { ProductImageCreateNestedManyWithoutProductsInput } from "./ProductImageCreateNestedManyWithoutProductsInput";
import { PromotionCreateNestedManyWithoutProductsInput } from "./PromotionCreateNestedManyWithoutProductsInput";
import { SliderCreateNestedManyWithoutProductsInput } from "./SliderCreateNestedManyWithoutProductsInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CategoryCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CategoryCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  category?: CategoryCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionRs?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionRu?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => ProductImageCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductImageCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductImageCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productImages?: ProductImageCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => PromotionCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PromotionCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PromotionCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  promotions?: PromotionCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sku?: string | null;

  @ApiProperty({
    required: false,
    type: () => SliderCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => SliderCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => SliderCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  sliders?: SliderCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleRs?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleRu?: string | null;
}

export { ProductCreateInput as ProductCreateInput };
