# Generated by Django 5.2.1 on 2025-05-14 06:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_topic_alter_homepage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='topic',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
