/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ProductUpdateManyWithoutCategoriesInput } from "./ProductUpdateManyWithoutCategoriesInput";
import { Type } from "class-transformer";
import { PromotionWhereUniqueInput } from "../../promotion/base/PromotionWhereUniqueInput";
import { SliderUpdateManyWithoutCategoriesInput } from "./SliderUpdateManyWithoutCategoriesInput";

@InputType()
class CategoryUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionRs?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionRu?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  parent?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProductUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => ProductUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  products?: ProductUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => PromotionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PromotionWhereUniqueInput)
  @IsOptional()
  @Field(() => PromotionWhereUniqueInput, {
    nullable: true,
  })
  promotion?: PromotionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => SliderUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => SliderUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => SliderUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  sliders?: SliderUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleRs?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleRu?: string | null;
}

export { CategoryUpdateInput as CategoryUpdateInput };
